[build]
  # Loyihangizning asosiy katalogi
  base = "/"
  
  # Build komandasi (Next.js uchun build komandasi)
  command = "npm run build"
  
  # Publish katalogi
  publish = "out"  # Agar Next.js ishlatayotgan bo'lsangiz, "out" papkasini belgilab qo'ying.
  
  # Functions katalogi (Agar ishlatsangiz)
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
